### PR TITLE
fix #7

### LINKED ISSUE #7: completing path at space throws error
```julia
julia> using FuzzyCompletions

julia> using REPL

julia> dir = mktempdir()
"/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_BzlNra"

julia> touch(joinpath(dir, "a file.txt"))
"/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_BzlNra/a file.txt"

julia> query = joinpath(dir, "a ")
"/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_BzlNra/a "

julia> REPL.REPLCompletions.complete_path(query, lastindex(query))
(REPL.REPLCompletions.Completion[REPL.REPLCompletions.PathCompletion("a file.txt")], 59:61, true)

julia> FuzzyCompletions.complete_path(query, lastindex(query))
ERROR: BoundsError: attempt to access 0-element Array{Char,1} at index [1]
Stacktrace:
 [1] getindex at ./array.jl:809 [inlined]
 [2] matchinds(::String, ::String; acronym::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/docview.jl:487
 [3] bestmatch at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/docview.jl:500 [inlined]
 [4] fuzzyscore(::String, ::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/docview.jl:510
 [5] fuzzyscore at /Users/fons/.julia/packages/FuzzyCompletions/575TE/src/FuzzyCompletions.jl:16 [inlined]
 [6] PathCompletion at /Users/fons/.julia/packages/FuzzyCompletions/575TE/src/FuzzyCompletions.jl:34 [inlined]
 [7] complete_path(::String, ::Int64; use_envpath::Bool, shell_escape::Bool) at /Users/fons/.julia/packages/FuzzyCompletions/575TE/src/FuzzyCompletions.jl:326
 [8] complete_path(::String, ::Int64) at /Users/fons/.julia/packages/FuzzyCompletions/575TE/src/FuzzyCompletions.jl:256
 [9] top-level scope at REPL[10]:1

```

### PR DESCRIPTION
**Pull request by aviatesk**
/cc @fonsp

### CODE REVIEW

File: src/FuzzyCompletions.jl [hunk 1]
```diff
@@ -253,6 +253,16 @@ function complete_keyword(s::Union{String,SubString{String}})
 end
 
 function complete_path(path::AbstractString, pos; use_envpath=false, shell_escape=false)
+    # https://github.com/JunoLab/FuzzyCompletions.jl/issues/7
+    if endswith(path, ' ')
+        # in order to keep type stability, we just return empty completion for this case
+        return Completion[], 0:-1, false
+        # return REPL.REPLCompletions.complete_path(
```
Comment (aviatesk) [inline src/FuzzyCompletions.jl:260]: @fonsp
I choose your option 1, because otherwise we end up looser return type (i.e. `Tuple{Union{Vector{FuzzyCompletions.Completion}, Vector{REPL.REPLCompletions.Completion}}, UnitRange{Int64}, Bool}`).
If you still want to get completions for this case, can you make an additional patch on Pluto.jl side ?

Comment (fonsp) [reply src/FuzzyCompletions.jl:260]: It's fine without completions, thanks!

**Comment by fonsp** [comment]
@aviatesk Can you also tag a version?

**Review by pfitzseb — APPROVED** [review]

**Comment by aviatesk** [comment]
> @aviatesk Can you also tag a version?

Of course, I will tag a patch version.

Thanks for double checking, @pfitzseb :)
